package ggt.KoordinatorPackage;

/**
* ggt/KoordinatorPackage/EInvalidAmountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class EInvalidAmountHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.KoordinatorPackage.EInvalidAmount value = null;

  public EInvalidAmountHolder ()
  {
  }

  public EInvalidAmountHolder (ggt.KoordinatorPackage.EInvalidAmount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.KoordinatorPackage.EInvalidAmountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.KoordinatorPackage.EInvalidAmountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.KoordinatorPackage.EInvalidAmountHelper.type ();
  }

}
