package ggt.StarterPackage;

/**
* ggt/StarterPackage/EInvalidCountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class EInvalidCountHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.StarterPackage.EInvalidCount value = null;

  public EInvalidCountHolder ()
  {
  }

  public EInvalidCountHolder (ggt.StarterPackage.EInvalidCount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.StarterPackage.EInvalidCountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.StarterPackage.EInvalidCountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.StarterPackage.EInvalidCountHelper.type ();
  }

}
