package ggt.KoordinatorPackage;

/**
* ggt/KoordinatorPackage/EStarterNoSuchElementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class EStarterNoSuchElementHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.KoordinatorPackage.EStarterNoSuchElement value = null;

  public EStarterNoSuchElementHolder ()
  {
  }

  public EStarterNoSuchElementHolder (ggt.KoordinatorPackage.EStarterNoSuchElement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.KoordinatorPackage.EStarterNoSuchElementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.KoordinatorPackage.EStarterNoSuchElementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.KoordinatorPackage.EStarterNoSuchElementHelper.type ();
  }

}
