package ggt.KoordinatorPackage;


/**
* ggt/KoordinatorPackage/EStarterNoSuchElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class EStarterNoSuchElement extends org.omg.CORBA.UserException
{
  public String s = null;

  public EStarterNoSuchElement ()
  {
    super(EStarterNoSuchElementHelper.id());
  } // ctor

  public EStarterNoSuchElement (String _s)
  {
    super(EStarterNoSuchElementHelper.id());
    s = _s;
  } // ctor


  public EStarterNoSuchElement (String $reason, String _s)
  {
    super(EStarterNoSuchElementHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class EStarterNoSuchElement
