package ggt;

/**
* ggt/KoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class KoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.Koordinator value = null;

  public KoordinatorHolder ()
  {
  }

  public KoordinatorHolder (ggt.Koordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.KoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.KoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.KoordinatorHelper.type ();
  }

}
