package ggt;


/**
* ggt/ProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Freitag, 25. April 2014 17:43 Uhr MESZ
*/

public interface ProcessOperations 
{
  String name ();

  // Methods for the other Processes
  void newNumber (int number, String senderName);
  void sendMarker (String terminator, int seqN);

  //Methods for the Starter
  void quit (String starterName);

  //Methods for the Koordinator
  void init (ggt.Process rightNeighbor, ggt.Process leftNeighbor, int startGGT, int delay, monitor.Monitor theMonitor, ggt.Koordinator koor);
  void startCalulation ();
  int getMi ();
} // interface ProcessOperations
