package ggt;


/**
* ggt/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public interface StarterOperations 
{
  String name ();

  //Methods for the Koordinator
  void createProcess (int count) throws ggt.StarterPackage.EInvalidCount;
  void exit ();
  void processExit ();
} // interface StarterOperations
