package ggt;


/**
* ggt/KoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public interface KoordinatorOperations 
{

  // Methods for the Process
  void registerProcess (ggt.Process process);
  void terminationCcheck (ggt.Process terminator, int seqN, boolean status);

  // Methods for the Starter
  void activateStarter (ggt.Starter starter, String starterName) throws ggt.KoordinatorPackage.EAlreadyExists;
  void deleteStarter (ggt.Starter starter);

  // Methods for the Monitor
  void registerMonitor (monitor.Monitor monitor);

  // Methods for the Client
  void startCalculation (int minProcesses, int maxProcesses, int minDelay, int maxDelay, int timeout, int startGGT) throws ggt.KoordinatorPackage.EInvalidAmount;
  ggt.Starter[] getStarterListe () throws ggt.KoordinatorPackage.EStarterNoSuchElement;
  void exit ();
} // interface KoordinatorOperations
