package ggt.KoordinatorPackage;


/**
* ggt/KoordinatorPackage/EInvalidAmount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class EInvalidAmount extends org.omg.CORBA.UserException
{
  public String s = null;

  public EInvalidAmount ()
  {
    super(EInvalidAmountHelper.id());
  } // ctor

  public EInvalidAmount (String _s)
  {
    super(EInvalidAmountHelper.id());
    s = _s;
  } // ctor


  public EInvalidAmount (String $reason, String _s)
  {
    super(EInvalidAmountHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class EInvalidAmount
