package ggt.KoordinatorPackage;

/**
* ggt/KoordinatorPackage/exAlreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Freitag, 25. April 2014 17:43 Uhr MESZ
*/

public final class exAlreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public ggt.KoordinatorPackage.exAlreadyExists value = null;

  public exAlreadyExistsHolder ()
  {
  }

  public exAlreadyExistsHolder (ggt.KoordinatorPackage.exAlreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggt.KoordinatorPackage.exAlreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggt.KoordinatorPackage.exAlreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggt.KoordinatorPackage.exAlreadyExistsHelper.type ();
  }

}
