package ggt.StarterPackage;


/**
* ggt/StarterPackage/EInvalidCount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Aufgabe2.idl
* Samstag, 26. April 2014 08:57 Uhr MESZ
*/

public final class EInvalidCount extends org.omg.CORBA.UserException
{
  public String s = null;

  public EInvalidCount ()
  {
    super(EInvalidCountHelper.id());
  } // ctor

  public EInvalidCount (String _s)
  {
    super(EInvalidCountHelper.id());
    s = _s;
  } // ctor


  public EInvalidCount (String $reason, String _s)
  {
    super(EInvalidCountHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class EInvalidCount
